### ISSUE TITLE
Install TaskCluster integration for this repository

### ISSUE THREAD

**Issue by davehunt** [mozilla-services/go-bouncer#105]
Please install https://github.com/integration/taskcluster for this repository so that TaskCluster will publish revisions and Treeherder will ingest these into https://treeherder.allizom.org/#/jobs?repo=go-bouncer (and https://treeherder.mozilla.org/#/jobs?repo=go-bouncer after the next deployment). This will allow us to then submit test results to Treeherder.

**Comment by davehunt** [comment]
@oremj are you able to take care of this?

**Comment by oremj** [comment]
I've added the integration to this repository, but have not added a `.taskcluster.yml` file.

**Comment by davehunt** [comment]
Thanks @oremj, there's no need for a `.taskcluster.yml` file, we're just ingesting the revisions into Treeherder.
