### ISSUE TITLE
e2e tests: remove xfail from product-details sync tests

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-services/go-bouncer#114]
Remove the xfail from`test_verify_product_details_is_in_sync_with_ship_it()`.

Currently the test is xfailed due to our CI not having access to ship-it. Once this is remedied we can remove this xfail. I'll follow up shortly with a bug number.

https://github.com/mozilla-services/go-bouncer/blob/master/tests/e2e/tests/test_smoketests.py#L27

**Comment by davehunt** [comment]
This is failing (as expected) over 900 times every week. Do we have a bug to track opening up access to ship-it? /cc @m8ttyB

**Comment by m8ttyB** [comment]
Unfortunately the team doesn't have the bandwidth this quarter to chase a remedy for this. I'm open to deleting this test until such time we can get traction from the ship-it team

**Comment by m8ttyB** [comment]
Closing this out, we've since removed this testcase. Exploring options for scoping a new plan, I'll file issues mapping out a solution once we've decided on a path.

**Comment by m8ttyB** [comment]
Opps, this is still in our code base. Reopening.
