### ISSUE TITLE
Stub attribution redirect

### ISSUE THREAD

**Issue by oremj** [mozilla-services/go-bouncer#34]
If the `attribution_code` parameter is set, redirect to the stub downloader service with the `product`, `os`, `lang` and `attribution_code` parameters set.

@pmac

**Comment by pmac** [comment]
Do we also include the `signature` parameter, or is that expected to be part of the `attribution_code`?

**Comment by oremj** [comment]
If we are still doing the signature parameter, it would be easier as a separate parameter.

**Comment by pmac** [comment]
I actually don't remember seeing in the spec how to send the HMAC signature. It makes most sense to me as a separate param. I'll do that. Does `signature` work for you, or would something like `attribution_sig` be better? Probably the latter is most obvious.

**Comment by oremj** [comment]
Did we decide to implement signature? I don't remember, but if we did, then `attribution_sig` is probably better.

**Comment by pmac** [comment]
I was under the impression that the signature was definitely required. The service on bedrock is already written. If it's not then that's fine but I've not heard anything that would suggest it's been removed from requirements, but things have been in flux to put it mildly.

**Comment by pmac** [comment]
Also `attribution_sig` works fine for me.

cc @alexgibson

**Comment by oremj** [comment]
Let's proceed with using the signature.
