### ISSUE TITLE
Limit RTAMO attribution to www referrals

### ISSUE THREAD

**Issue by muffinresearch** [mozilla-services/go-bouncer#347]
## Description

Ignore attribution for RTAMO if the referral wasn't from www.mozilla.org , using a referer header check.

---

#### Success Criteria

- [ ] RTAMO attribution should be present if the user was referred by www.mozilla.org and all other validation is successful.
- [ ] RTAMO attribution should be ignored if the user did not start on www.mozilla.org.

**Comment by muffinresearch** [comment]
@moz-astults  Hi, as this is a dependency of other work we need to carry out on AMO, would it be possible to get a rough idea of when this might be worked on? Also please let me know if you have any questions or need additional context.

**Comment by moz-astults** [comment]
@muffinresearch I am hoping to start looking into this tomorrow or early next week. I'll definitely reach out on slack if I need more context. Thanks!
