### ISSUE TITLE
Add support for macOS attribution data

### ISSUE THREAD

**Issue by willdurand** [mozilla-services/go-bouncer#351]
See: https://docs.google.com/document/d/1NLobogbVfSYofcm7b61tesTirlXpmxwIRYd6Gsd3tt8/edit#heading=h.xrdvvhrlt660

**Comment by ncalexan** [comment]
Functionally, I think this will require the bouncer to recognize that macOS downloads need to be redirected to the stub attribution service in the same manner as Windows downloads are redirected.  See https://github.com/mozilla-services/go-bouncer/blob/4ffffc67ed87e8e2dee8c831ddd9d2d0c3efc170/handlers.go#L391-L392.
