### ISSUE TITLE
Enable pyup.io for taking care of dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla-services/go-bouncer#65]
We want to enable [pyup.io](https://pyup.io/) for our projects to take care of automating the updates to our dependencies. Here's what's needed:

- [x] Move dependencies out of `tox.ini` and into requirements files. See https://github.com/mozilla/PyPOM/commit/ad21988d0364843808c07f3aaa656c6c16b971b2 for an example of this.
- [x] Add repository to pyup.io (@davehunt can take care of this once the above is merged).
- [x] Add pyup.io badges for updates and python 3 readyness. See https://github.com/mozilla/PyPOM/commit/931c41b964f1c9950983c078d0583ef708ac8af9 for an example of this.

**Comment by stephendonner** [comment]
https://github.com/mozilla-services/go-bouncer/pull/66 took care of the 1st part of this; marked it as done!

**Comment by davehunt** [comment]
I've requested access for pyup.io for the mozilla-services organisation. Once this is granted I can take care of the second item.

**Comment by oremj** [comment]
@jvehent what's the process for adding integrations?

**Comment by jvehent** [comment]
@oremj: blocked on https://github.com/mozilla-services/github-management/issues/3

**Comment by jvehent** [comment]
I've added this integration using the `mozcloudsec` account that has limited privileges in the org. Let me know if that solves the need.

**Comment by davehunt** [comment]
This has been completed.
